Error in file
Exception type: TypeError
Exception message: Index(...) must be called with a collection of some kind, 'Glass type' was passed
Stack trace:
File: Submissions/15095987.py
Line: 29
Func.Name: <module>
Message: 'attributes': pd.DataFrame(data, columns="Glass type") ,

File: /mnt/data/Linux/applications/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py
Line: 432
Func.Name: __init__
Message: data, axes=dict(index=index, columns=columns), dtype=dtype, copy=copy

File: /mnt/data/Linux/applications/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py
Line: 224
Func.Name: _init_mgr
Message: axe, axis=self._get_block_manager_axis(a), copy=False

File: /mnt/data/Linux/applications/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py
Line: 1215
Func.Name: reindex_axis
Message: new_index = ensure_index(new_index)

File: /mnt/data/Linux/applications/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py
Line: 5357
Func.Name: ensure_index
Message: return Index(index_like)

File: /mnt/data/Linux/applications/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py
Line: 422
Func.Name: __new__
Message: raise cls._scalar_data_error(data)

