Error in file
Exception type: AttributeError
Exception message: 'DataFrame' object has no attribute 'data'
Stack trace:
File: Submissions/18016899.py
Line: 30
Func.Name: <module>
Message: 'attributes': pd.DataFrame(data.data, columns=data.names),

File: /mnt/data/Linux/applications/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py
Line: 5274
Func.Name: __getattr__
Message: return object.__getattribute__(self, name)

