Error in file
Exception type: AttributeError
Exception message: 'DataFrame' object has no attribute 'species'
Stack trace:
File: Submissions/18093369.py
Line: 51
Func.Name: <module>
Message: y_train = testData['train']['target'].species

File: /mnt/data/Linux/applications/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py
Line: 5274
Func.Name: __getattr__
Message: return object.__getattribute__(self, name)

